import { AlertTriangle, BookOpen, Calculator, Database, Scale } from "lucide-react";
import { Card, CardHeader, SyntheticBadge } from "@/components/ui/primitives";

const FORMULAS: [string, string, string][] = [
  ["Net burn", "Monthly burn − MRR × gross margin", "Cash actually leaving each month after gross profit."],
  ["Runway", "Cash ÷ net burn (capped at 60 months)", "Months until cash runs out at today's pace."],
  ["LTV", "ARPU × gross margin ÷ monthly churn", "Gross profit one customer brings over their lifetime."],
  ["LTV:CAC", "LTV ÷ customer acquisition cost", "Return on each rupee of acquisition. ≥ 3× is the common benchmark."],
  ["Burn multiple", "Net burn ÷ net new MRR", "Rupees burned per rupee of new recurring revenue. < 2× is efficient."],
  ["Growth rate", "Average month-on-month MRR growth", "Momentum; compounds in the projection (capped at 30%/mo)."],
];

const LIMITS = [
  ["Synthetic labels", "Every failure label is generated by a formula plus noise. Metrics show how well the model recovers that formula, not real-world accuracy."],
  ["Missing factors", "Market timing, competition, regulation, founder dynamics and macro conditions are not modelled."],
  ["Self-reported inputs", "Scores are only as good as the numbers entered. Optimistic inputs give optimistic scores."],
  ["Probabilities, not guarantees", "A 20% risk means roughly 1 in 5 similar synthetic startups failed, not that this one will or will not."],
  ["Association, not causation", "What-if and action-plan effects show how the model responds to changes. They do not prove that making the change causes the outcome."],
  ["Calibration edges", "Isotonic calibration is a step function, so near 0% or 100% small changes may not move the score."],
  ["Out-of-range inputs", "Values beyond the training data's 1st–99th percentile are clipped and flagged as less reliable."],
  ["Offline fallback", "Without the API, the browser uses an uncalibrated logistic regression on the same features (test ROC-AUC ≈ 0.90). Its probabilities differ from the API's."],
];

export default function Methodology() {
  return (
    <div className="space-y-5">
      <Card glow className="border-medium/40">
        <div className="flex flex-wrap items-start gap-4">
          <AlertTriangle className="h-6 w-6 shrink-0 text-medium" />
          <div className="flex-1">
            <div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-fg">This is synthetic data</h2><SyntheticBadge /></div>
            <p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted">
              The bundled dataset (6,000 startups across 7 sectors and 3 stages) is generated by <code className="num text-fg">src/data_generation.py</code> from
              startup-finance relationships plus random noise. No real company data is used. Use every output as decision support, never as a guarantee or the sole
              basis for a funding decision.
            </p>
          </div>
        </div>
      </Card>

      <div className="grid gap-4 xl:grid-cols-2">
        <Card>
          <CardHeader title="Finance theory" subtitle="Feature engineering, computed automatically from your inputs." action={<Calculator className="h-5 w-5 text-teal" />} />
          <dl className="space-y-3">
            {FORMULAS.map(([name, f, why]) => (
              <div key={name} className="rounded-xl bg-[var(--surface)] p-3">
                <dt className="flex flex-wrap items-baseline justify-between gap-2">
                  <span className="font-medium text-fg">{name}</span>
                  <code className="num text-xs text-teal">{f}</code>
                </dt>
                <dd className="mt-1 text-xs text-muted">{why}</dd>
              </div>
            ))}
          </dl>
        </Card>
        <Card>
          <CardHeader title="How the data and labels are generated" action={<Database className="h-5 w-5 text-indigo" />} />
          <ol className="list-decimal space-y-2 pl-5 text-sm leading-relaxed text-muted">
            <li>Sector and stage drive team size, burn, revenue fraction, gross margin and funding rounds.</li>
            <li>Churn rises when growth is weak; LTV follows ARPU × margin ÷ churn; CAC is drawn around LTV ÷ 2.3.</li>
            <li>A latent risk adds up runway shortfall, churn, low growth, weak LTV:CAC, low founder experience and few rounds, plus Normal noise.</li>
            <li>The top 32% by latent risk are labelled “failed within 24 months”.</li>
            <li>4–8% of experience, margin, churn, CAC and LTV values are blanked, and 25 burn values are multiplied by 10, to test robustness.</li>
          </ol>
          <CardHeader className="mt-6" title="Model pipeline" action={<Scale className="h-5 w-5 text-teal" />} />
          <p className="text-sm leading-relaxed text-muted">
            80/20 stratified split; winsorise to training 1st/99th percentiles; median imputation with missing indicators; scaling; one-hot categories. Logistic
            Regression, Random Forest and Gradient Boosting are compared with 5-fold CV. The best ROC-AUC wins, and a simpler model within 0.01 is preferred. The winner is
            calibrated with isotonic regression, and the test set is used once. Explanations replace each factor group with the training median and re-score.
          </p>
        </Card>
      </div>

      <Card>
        <CardHeader title="Limitations" subtitle="Read these before acting on any score." action={<BookOpen className="h-5 w-5 text-muted" />} />
        <ul className="grid gap-3 md:grid-cols-2">
          {LIMITS.map(([t, b]) => (
            <li key={t} className="rounded-xl border border-[var(--border)] p-4">
              <div className="font-medium text-fg">{t}</div>
              <p className="mt-1 text-sm leading-relaxed text-muted">{b}</p>
            </li>
          ))}
        </ul>
      </Card>
    </div>
  );
}
