[theme]
base = "light"
primaryColor = "#0E7C7B"
backgroundColor = "#F2F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F1B2D"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[server]
headless = true

[browser]
gatherUsageStats = false
